version: '3'
services:
  #nginx:
  #  container_name: nginx
  #  build: ./requirements/nginx
  #  ports:
  #    - 443:443
  #  networks:
  #    - inception_network
  #  restart: always
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    networks:
      - inception_network
    ports:
      - "3306:3306"
    restart: always
  wordpress:
    stdin_open: true
    tty: true
    container_name: wordpress
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    networks:
      - inception_network
    ports:
      - "9000:9000"
    restart: always


networks:
  inception_network:
