version: '3.7'
services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - 443:443
    networks:
      - inception_network
    restart: unless-stopped

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    networks:
      - inception_network
    ports:
      - "3306:3306"
    restart: unless-stopped
    env_file:
      - ./.env
    #debug
    stdin_open: true
    tty: true


  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    networks:
      - inception_network
    ports:
      - "9000:9000"
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - wordpress_volume:/var/www/html/wordpress/
    #debug
    stdin_open: true
    tty: true


networks:
  inception_network:

volumes:
  wordpress_volume:
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/inception/srcs/data/html/wordpress/
      o: bind
